CREATE TABLE coins (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   uuid TEXT NOT NULL UNIQUE,
   symbol TEXT NOT NULL,
   name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_coins_uuid_unique ON coins(uuid);
