CREATE TABLE coin_data (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   coin_id INTEGER NOT NULL,
   price REAL NOT NULL,
   market_cap REAL NOT NULL,
   ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (coin_id) REFERENCES coins(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_coin_data_coin_id ON coin_data(coin_id);
